### PR TITLE
[WIP] Script to extract DDG results

### PR DESCRIPTION
**Pull request by hannahbaumann**
## Licensing agreement
* [x] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

### CODE REVIEW

**Comment by hannahbaumann** [comment]
This is just a very rough analysis script. Potential things to add: 
- command line options for file path names
- make this compatible to be used with cinnabar
- Handling of cases where simulations did not complete

**Comment by hannahbaumann** [comment]
This outputs a .csv file that can be read into a dict using:
```
import csv
from pprint import pprint

calculated_data = {}
calculated_filename = 'ddg.csv'

with open(calculated_filename, 'r') as fd:
    rd = csv.reader(fd)
    headers = next(rd)
    for row in rd:
        tag = row[0] + "->" + row[1]
        calculated_data[tag] = {}
        calculated_data[tag]['ligand_i'] = row[0]
        calculated_data[tag]['ligand_j'] = row[1]
        calculated_data[tag]['dG'] = float(row[2])
        calculated_data[tag]['ddG'] = float(row[3])

pprint(calculated_data)
```
Plotting with cinnabar is possible if experimental data are provided following this notebook:
https://github.com/OpenFreeEnergy/ExampleNotebooks/blob/main/plotting_rbfes_with_cinnabar/PlottingFreeEnergiesUsingCinnabar.ipynb

**Comment by IAlibay** [comment]
@hannahbaumann is there any chance we can match the gather output TSV format?

**Comment by hannahbaumann** [comment]
@IAlibay now the output should match the gather output. I realized that instead of using my old script I could have also just modified gather to work with this result structure, would that be better or do you think this script also works?

**Comment by IAlibay** [comment]
> @IAlibay now the output should match the gather output. I realized that instead of using my old script I could have also just modified gather to work with this result structure, would that be better or do you think this script also works?

Thanks I'll review a bit later today. Re: modifying gather, I think long term we should do that (i.e. pass multiple directories or just a lot of results JSONs that could be duplicate), but I see this script as part of testing things towards that process.

**Review by IAlibay — APPROVED** [review]

**Pull request merged**
