### PR TITLE
Prepare tyk2

### PR DESCRIPTION
**Pull request by BillSwope**
## Input submission checklist

* [ x] created a directory for each system based on the [template directory][templates]
* [ x] named and placed the directory with the following pattern: `input_structures/prepared_structures/<set_name>/<system_name>`

For each submitted directory:

* [x ] filled in system preparation details in the `PREPARATION_DETAILS.md` file
* [x ] added a PDB file with the protein named `protein.pdb`
* [x ] removed any cofactors from the PDB file and placed them in `cofactors.sdf`
* [ x] did not re-protonate the residues, but left protonation state of the protein unchanged
* [x ] kept cystallographic waters and metals in the PDB file
* [ x] tested the PDB and, if available, cofactors.sdf file using the [input validation script][input_validation]
* [x ] copied over the ligands SDF file to a file named `ligands.sdf` and removed any duplicate binding modes or protonation states, keeping the more favorable state

## Licensing agreement
* [ x] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

### CODE REVIEW

**Comment by hannahbaumann** [comment]
Thank you @BillSwope , this looks great! Just two small things, could you add the Maestro version number to the preparation instructions? And I noticed that the prepared files are present twice, ones in the `input_structures/prepared_structures/jacs_set/tyk2/` folder and also in the `input_structures/prepared_structures/jacs_set/tyk2/prepare_tyk2/` folder. If the later files are a duplicate of  the former ones, could the files in the `...prepare_tyk2/` be deleted?

**Comment by BillSwope** [comment]
Hannah, yes. I’ll add the version number of Maestro to the description.  And, yes, the files are duplicated in the prepare_tyk2 subdirectory.  This gets at some of my confusion about the GitHub instructions.  I didn’t see the point of that part of the instructions.  Was I to make that directory? And where in the file structure was that supposed to be made? I don’t think you really want that in the repo, right?  So where is that directory and why do we need it?  Also the git add instructions where you list the files, do you issue that while being in the current directory where the files are or do you give some sort of path from where your current directory is to where the files are?  You could also mention how to update your clone so it is in sync with the OpenFE repo.  (Or is the clone on your local machine meant to be only consistent with your fork (a snapshot of the repo) and not the repo itself. I found it useful to read what the others had done so it would be nice if we could make the clone consistent with the repo.  Sorry for the rambling.  I guess I still have a lot to learn about GitHubs. Thanks for the prompt freedback.   …BillSent from iPhoneOn Jul 17, 2024, at 12:48 AM, Hannah Baumann ***@***.***> wrote:﻿
Thank you @BillSwope , this looks great! Just two small things, could you add the Maestro version number to the preparation instructions? And I noticed that the prepared files are present twice, ones in the input_structures/prepared_structures/jacs_set/tyk2/ folder and also in the input_structures/prepared_structures/jacs_set/tyk2/prepare_tyk2/ folder. If the later files are a duplicate of  the former ones, could the files in the ...prepare_tyk2/ be deleted?

**Comment by hannahbaumann** [comment]
@BillSwope thank you so much for the clarification! I'm sorry the instructions for creating the directories were confusing!
The directory for the prepared files is the following for this TYK2 example:
`IndustryBenchmarks2024/industry_benchmarks/input_structures/prepared_structures/jacs_set/tyk2/`
We already ended up creating all the directories for the different sets (e.g. jacs_set) and systems (e.g. tyk2), so now everyone can deposit their structures under
`IndustryBenchmarks2024/industry_benchmarks/input_structures/prepared_structures/<name of set>/<name of system>/`.
So this means that the folder structure is already present in the GitHub repo (also in your local copy/fork of the GitHub repo) and you can deposit the prepared files in that folder.
So as a first step you copy the files into the correct folder, e.g. 
`cp ligands.sdf IndustryBenchmarks2024/industry_benchmarks/input_structures/prepared_structures/jacs_set/tyk2/` and then you upload/add them to Github using `git add`.
For adding the files to the repo (`git add`) you don't necessarily have to be in the directory, but you can be in some directory within you repo and then give the file path, e.g.
if you already are in the folder for `tyk2` you can just do 
`git add ligands.sdf`
if you are not in the folder you can add the path that leads to the file, like e.g.
`git add input_structures/prepared_structures/jacs_set/tyk2/ligands.sdf`.

Regarding having the most up-to-date version of the repo: It is possible to update your fork (and your local copy of the fork) and integrate the newest changes from the core repo. Here are some instructions on how to do this: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
If you make the changes via the web UI, you can afterwards update your local copy using `git pull`.

Please let me know if this is unclear and I'm happy to discuss in more detail!

I deleted the duplicate files in this PR. If you want to add the maestro version in your local version, you can do `git pull` to first update the local copy (i.e. also deleting those files in your local copy) before making the changes.

**Comment by BillSwope** [comment]
Perfectly clear. I’ll make all your suggested fixes and update. I know you must be crazy busy so thank you for taking the time to help. I’ll get to work on the next protein systems.  …BillSent from iPhoneOn Jul 17, 2024, at 5:31 AM, Hannah Baumann ***@***.***> wrote:﻿
@BillSwope thank you so much for the clarification! I'm sorry the instructions for creating the directories were confusing!
The directory for the prepared files is the following for this TYK2 example:
IndustryBenchmarks2024/industry_benchmarks/input_structures/prepared_structures/jacs_set/tyk2/
We already ended up creating all the directories for the different sets (e.g. jacs_set) and systems (e.g. tyk2), so now everyone can deposit their structures under
IndustryBenchmarks2024/industry_benchmarks/input_structures/prepared_structures/<name of set>/<name of system>/.
So this means that the folder structure is already present in the GitHub repo (also in your local copy/fork of the GitHub repo) and you can deposit the prepared files in that folder.
So as a first step you copy the files into the correct folder, e.g.
cp ligands.sdf IndustryBenchmarks2024/industry_benchmarks/input_structures/prepared_structures/jacs_set/tyk2/ and then you upload/add them to Github using git add.
For adding the files to the repo (git add) you don't necessarily have to be in the directory, but you can be in some directory within you repo and then give the file path, e.g.
if you already are in the folder for tyk2 you can just do
git add ligands.sdf
if you are not in the folder you can add the path that leads to the file, like e.g.
git add input_structures/prepared_structures/jacs_set/tyk2/ligands.sdf.
Regarding having the most up-to-date version of the repo: It is possible to update your fork (and your local copy of the fork) and integrate the newest changes from the core repo. Here are some instructions on how to do this:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork
If you make the changes via the web UI, you can afterwards update your local copy using git pull.
Please let me know if this is unclear and I'm happy to discuss in more detail!
I deleted the duplicate files in this PR. If you want to add the maestro version in your local version, you can do git pull to first update the local copy (i.e. also deleting those files in your local copy) before making the changes.

**Comment by hannahbaumann** [comment]
I will go ahead and close this PR since a new version of the files were uploaded in PR #101 . Please feel free to reopen this PR if necessary!

**Pull request closed without merging**
