### PR TITLE
Add test for input validation of a protein with PTM

### PR DESCRIPTION
**Pull request by hannahbaumann**
## Input submission checklist

* [ ] created a directory for each system based on the [template directory][templates]
* [ ] named and placed the directory with the following pattern: `input_structures/prepared_structures/<set_name>/<system_name>`

For each submitted directory:

* [ ] filled in system preparation details in the `PREPARATION_DETAILS.md` file
* [ ] added a PDB file with the protein named `protein.pdb`
* [ ] removed any cofactors from the PDB file and placed them in `cofactors.sdf`
* [ ] kept cystallographic waters and metals in the PDB file
* [ ] tested the PDB and, if available, cofactors.sdf file using the [input validation script][input_validation]
* [ ] copied over the ligands SDF file to a file named `ligands.sdf`
* [ ] copied over the edges CSV file to a file named `edges.csv`

## Licensing agreement
* [x] I agree to release these inputs under the combined MIT and CCBY SA 4.0 licenses of this repository

[templates]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks
[input_validation]: https://github.com/OpenFreeEnergy/IndustryBenchmarks2024/tree/main/industry_benchmarks/utils/input_validation.py

### CODE REVIEW

**Comment by hannahbaumann** [comment]
@IAlibay : I added a test that checks that the input validation script fails when a protein with PTM (in this case CDK2 with TPO) is given. This is just a general test, or should this check specific errors associated with loading of structures with PTM?

**Review by IAlibay — CHANGES_REQUESTED** [review]
Thanks for working on this @hannahbaumann - I'm running the tests and getting a failure though, are you sure you are getting a failure with this when using the latest gufe?

**Comment by hannahbaumann** [comment]
Ah, you're right, this was with an older gufe version with the old ProteinComponent. Can you think of a system with PTM that should still fail?

**Comment by IAlibay** [comment]
@hannahbaumann the TYS residue in thrombin is one which we should expect to fail - I've spent the last hour trying to get the file to work, but it needs extra attention on protein capping and I've ran out of time :(

**Comment by IAlibay** [comment]
@hannahbaumann here's the PDB for a capped thrombin that does fail because of TYS.

[thrombin_core_protein_capped.zip](https://github.com/user-attachments/files/15613291/thrombin_core_protein_capped.zip)

**Comment by hannahbaumann** [comment]
@IAlibay : I updated the tests, one for the Thrombin with PTM where now indeed Simulations fail, and one where I converted the TYS back to TYR and that one runs successfully.

**Review by IAlibay — APPROVED** [review]

**Pull request merged**
